local:
  # in this case we can use defaults:
  # host:         localhost
  # user:         same
  # dir:          .
  # runq_host:    localhost
  # runq_port:    env var or default
  # runweb_host:  localhost
  # runweb_port:  env var or default
  workers:
    - run_class:    Run::Aurora
      count:        1
      group:        topl
      user:         topl
      engine:       simulator
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

    - run_class:    Run::Dummy
      count:        3
      group:        topl
      user:         topl
      engine:       dummy
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

#    - run_class:    Run::Calibrator
#      count:        1
#      group:        topl
#      user:         topl
#      engine:       calibrator
#      engine_opts:
#        jar_file:   /home/vjoel/topl/calib/tmp/fdcalibrate.jar
#        sensor_dir: /home/vjoel/topl/calib/tmp/
#      cost:         0
#      speed:        1
#      priority:     1
#      retry_delay:  10

vii-aurora:
  host:         vii.path.berkeley.edu
  user:         aurora
  dir:          simx-dev
  runq_host:    relteq-db.dyndns.org
  runq_port:    9096
  runweb_host:  relteq-db.dyndns.org
  runweb_port:  9097
  workers:
    - run_class:    Run::Aurora
      count:        4
      group:        topl
      user:         topl
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

vii-vjoel:
  host:         vii.path.berkeley.edu
  user:         vjoel
  dir:          simx-dev
  runq_host:    relteq-db.dyndns.org
  runq_port:    9096
  runweb_host:  relteq-db.dyndns.org
  runweb_port:  9097
  workers:
    - run_class:    Run::Aurora
      count:        4
      group:        vjoel
      user:         vjoel
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

    - run_class:    Run::Dummy
      count:        3
      group:        vjoel
      user:         vjoel
      engine:       dummy
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10
    
    - run_class:    Run::Calibrator
      count:        4
      group:        vjoel
      user:         vjoel
      engine:       calibrator
      engine_opts:
        jar_file:   /home/vjoel/topl/calib/fdcalibrate.jar
        sensor_dir: /home/vjoel/topl/calib/
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10
