local:
  # in this case we can use defaults:
  # host:         localhost
  # user:         same
  # dir:          .
  # runq_host:    localhost
  # runq_port:    env var or default
  # apiweb_host:  localhost
  # apiweb_port:  env var or default
  workers:
    - run_class:    Run::Aurora
      count:        2
      group:        relteq
      user:         relteq
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

# TOPL users who are using the relteq front-end can use workers on
# the vii server.
vii:
  host:         vii.path.berkeley.edu
  user:         aurora
  dir:          simx-rt-topl-staging
  runq_host:    relteq-db.dyndns.org
  runq_port:    8596
  apiweb_host:  relteq-db.dyndns.org
  apiweb_port:  8597
  workers:
    - run_class:    Run::Aurora
      count:        8
      group:        topl
      user:         topl
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

relteq-db:
  host:         simx
  user:         worker
  dir:          simx-staging
  runq_host:    localhost
  runq_port:    8596
  apiweb_host:  localhost
  apiweb_port:  8597
  workers:
    - run_class:    Run::Aurora
      count:        2
      group:        relteq
      user:         relteq
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10
