local:
  # in this case we can use defaults:
  # host:         localhost
  # user:         same
  # dir:          .
  # runq_host:    localhost
  # runq_port:    env var or default
  # apiweb_host:  localhost
  # apiweb_port:  env var or default
  workers:
    - run_class:    Run::Aurora
      count:        2
      group:        topl
      user:         topl
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

    - run_class:    Run::Dummy
      count:        3
      group:        topl
      user:         topl
      engine:       dummy
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

vii:
  host:         vii.path.berkeley.edu
  user:         aurora
  dir:          simx
  runq_host:    vii.path.berkeley.edu
  runq_port:    8096
  apiweb_host:  vii.path.berkeley.edu
  apiweb_port:  8097
  workers:
    - run_class:    Run::Aurora
      count:        8
      group:        topl
      user:         topl
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

path:
  host:         gateway.path.berkeley.edu
  user:         vjoel
  dir:          simx
  runq_host:    vii.path.berkeley.edu
  runq_port:    8096
  apiweb_host:  vii.path.berkeley.edu
  apiweb_port:  8097
  workers:
    - run_class:    Run::Aurora
      count:        4
      group:        topl
      user:         topl
      engine:       simulator|calibrator|report generator|report exporter
      cost:         0
      speed:        1
      priority:     1
      retry_delay:  10

