deploy:
  host: simx
  path: simx-dev
runq:
  port: 9096
  log level: debug
apiweb:
  port: 9097
  log level: debug
  simx_group: relteq
  simx_user: relteq
dpool:
  socket: dpool.sock
  log level: debug
worker:
  config file: dev.yaml
  log level: debug
aws:
  mock: true
  ###s3 bucket: relteq-uploads-dev
db:
  url: postgres://redmine:topl5t6y7u8i@relteq-db.dyndns.org/relteq-dev
