deploy:
  host: simx
  path: simx
runq:
  port: 8096
  log level: info
apiweb:
  port: 8097
  log level: info
dpool:
  socket: dpool.sock
  log level: debug
worker:
  config file: master.yaml
  log level: info
aws:
  s3 bucket: relteq-uploads
db:
  url: postgres://redmine:topl5t6y7u8i@relteq-db.dyndns.org/relteq
