deploy:
  host: simx
  path: simx
runq:
  port: 8096
  log level: info
runweb:
  port: 8097
  log level: info
dbweb:
  port: 8098
  log level: info
worker:
  config file: master.yaml
  log level: info
aws:
  s3 bucket: relteq-uploads
#db:
#  url: sqlite://var/data/master.sqlite
