deploy:
  host: aurora@vii
  path: simx
runq:
  port: 8096
  log level: debug
apiweb:
  port: 8097
  log level: debug
dpool:
  socket: dpool.sock
  log level: debug
worker:
  config file: vii.yaml
  log level: debug
aws:
  mock: true
db:
  url: sqlite://var/data/simx.sqlite
