deploy:
  host: aurora@vii
  path: simx
runq:
  port: 9096
  log level: debug
apiweb:
  port: 9097
  log level: debug
worker:
  config file: vii.yaml
  log level: debug
aws:
  mock: true
db:
  url: sqlite://var/data/simx.sqlite
