#!/usr/bin/env ruby

# Script for running the dummy worker from command line. See also the
# worker-manager for running workers as child procs of a daemon parent.

topdir = File.expand_path("..")
libdir = File.join(topdir, "lib")
$LOAD_PATH.unshift libdir

require 'worker/worker'
require 'worker/run/dummy'

Socket.do_not_reverse_lookup = true

worker = Worker.new(Run::Dummy,
  "runq_host"    => ENV["RUNQ_HOST"] || 'localhost',
  "runq_port"    => ENV["RUNQ_PORT"] || 8096,
  "group"        => "topl",
  "user"         => "topl",
  "engine"       => "dummy",
  "cost"         => 0,
  "speed"        => 1,
  "priority"     => 1,
  "retry_delay"  => 10,
  "logdev"       => $stderr
)

worker.execute
